### ISSUE TITLE
Any way to edit ironman save?

### ISSUE THREAD

**Issue by AotoriChiaki** [timbuntu/ck3-iron-patcher#1]
How did you find the pattern, is their any way to edit ironman save?

**Comment by timbuntu** [comment]
The way I found it was basically just by quick trial and error.

 I created two similiar savegames with the only difference being that ironman is enabled in one, and disabled in the other.
Then I compared those two savegames and played around a bit with the values that differed between the two of them.

So sadly I don't actually know the save format or anything. According to the [CK3 Wiki](https://ck3.paradoxwikis.com/Modding#Save_game_editing) `"It is not possible to edit an ironman save!"`, although I think they might be referring to it not being possible as easily as for "normal" saves, for which it seems you can just do that with a text editor.
I didn't look any further into the savegame though, so I don't know if there is any other way to edit ironman saves. But theoretically it should be possible.
